### ISSUE TITLE
MaxLights crashes when uploading from Web UI

### ISSUE THREAD

**Issue by MrChubbs** [stringandstickytape/MaxLights#3]
When trying to save my diagram with Screen Capture in the Web UI the MaxLights app force closes without saving the diagram. This has been attempted on multiple lights (Lifx A9 and Lifx Lightstrip 120")

**Comment by MrChubbs** [comment]
Exception found in Event Viewer

Application: MaxLights.exe
CoreCLR Version: 6.0.722.32202
.NET Version: 6.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'SharpDX.DXGI, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1'. The system cannot find the file specified.
File name: 'SharpDX.DXGI, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1'
   at MaxLifxCore.ScreenCaptureEngine..ctor(Int32 monitor)
   at MaxLifxCore.SignalProcessors.UshortScreenListCapture.GetHsbs(AppController controller, Light light, StringBuilder debug, List`1& hues, List`1& sats, List`1& bris) in C:\Projects\MaxLights\MaxLifxCore\SignalProcessors\UshortScreenListCapture.cs:line 129
   at MaxLifxCore.SignalProcessors.UshortScreenListCapture.GetLatestHsbListValues(AppController controller, Light light, String outputSocketName, StringBuilder debug) in C:\Projects\MaxLights\MaxLifxCore\SignalProcessors\UshortScreenListCapture.cs:line 84
   at MaxLifxCore.SignalReceivers.Light.Process() in C:\Projects\MaxLights\MaxLifxCore\SignalReceivers\Light.cs:line 101
   at MaxLifxCore.AppController.<Run>b__62_0() in C:\Projects\MaxLights\MaxLifxCore\AppController.cs:line 299
   at System.Threading.Thread.StartCallback()

**Comment by stringandstickytape** [comment]
Judging from " FileNotFoundException: Could not load file or assembly
'SharpDX.DXGI", looks like it's having difficulty finding SharpDX.DXGI.dll
which should live in the same folder as the main MaxLights.exe file.  Might
be worth re-extracting the release zip file again in case that particular
binary is somehow corrupt...

Let me know how you get on...

**Comment by DesertRunner76** [comment]
Hi,

I want to use this for the Ambiilight feature but I'm curious how I set it up so it captures a portion of the screen colour but always displays the colour at 100% brightness. It captures colour well at the moment but the brightness is always changing and is usually very low.

Thanks.
